### ISSUE TITLE
User access removed, access is now via a team

### ISSUE THREAD

**Issue by NickWalt01** [moj-analytical-services/criminal_history_sankey#3]
Hi there

The user Mwillia85 had Direct Member access to this repository and access via a team.

Access is now only via a team.

You may have less access it is dependant upon the teams access to the repo.

If you have any questions, please post in (#ask-operations-engineering)[https://mojdt.slack.com/archives/C01BUKJSZD4] on Slack.

This issue can be closed.

**Comment by Mwillia85** [comment]
Hi Nick - GiT etc. is a bit of a black box for me but originally I was an admin for this criminal history sankey. I'd like to retain that please. I lead the criminal history team and this sankey forms part of our annual national statistics publication. Given the churn in my team I'd like to maintain admin so I can pull in my SEOs etc. closer to publication time to contribute/do the actual work. When I first joined we had the issue of Yu Zhang being the only admin and she retired and there was then a painful period of me getting added as an admin. Why does that permission keep being blocked - yet retained for Katie Lovewell in my team who may leave the organisation in the shorter term. Appreciate a steer. Cheers

**Comment by NickWalt01** [comment]
Hello @Mwillia85, I've added you to the admin team for this repo. To add users to the repo would now be via a team, ie is -criminal-history-sankey-admin-team, criminal-history-sankey-team, etc. A user can request to join a team or ask to be added to a team via the Slack channel #ask-operations-engineering. You can be in multiple teams and be a team maintainer which means you control a team users. Sorry for the delay I was OOO last week for a quicker response the team at #ask-operations-engineering can help set up teams / team members access to repos
